#pragma once

#if defined(BUILDCONFIG_EMBEDDED_BUILD) && (defined(BUILDCONFIG_TESTING_BUILD) || defined(BUILDCONFIG_FUZZING_BUILD))
#error AMBIGUOUS BUILD CONFIG
#endif

#if defined(BUILDCONFIG_TESTING_BUILD) && (defined(BUILDCONFIG_EMBEDDED_BUILD) || defined(BUILDCONFIG_FUZZING_BUILD))
#error AMBIGUOUS BUILD CONFIG
#endif

#if defined(BUILDCONFIG_FUZZING_BUILD) && (defined(BUILDCONFIG_EMBEDDED_BUILD) || defined(BUILDCONFIG_TESTING_BUILD))
#error AMBIGUOUS BUILD CONFIG
#endif